baseurl = "/"
title = "Data science in genomics & related things"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Sina R&uuml;eger"
disqusShortname = "sinarueeger-github-io"
googleAnalytics = "XXX"
publishDir = "../sinarueeger.github.io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableEmoji = true
enablefa = true

[Author]
    name = "Sina Rüeger"
    profile = "https://google.com/+XXX"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Sina Rüeger"
    description = "Data science in genetics & related things"
    github = "https://github.com/sinarueeger"
    linkedin = "https://www.linkedin.com/in/sinarueeger/"
    twitter = "https://twitter.com/sinarueeger"
    email = "sina.rueeger@gmail.com"
  gplus = "https://scholar.google.com/citations?view_op=list_works&hl=de&authuser=1&user=OD9gCh4AAAAJ"
    opengraph = false
    shareTwitter = false
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    color_theme = "red"

[Permalinks]
    post = "/:year/:month/:day/:filename/"
    

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2

[[menu.main]]
    name = "Contact"
    url = "/page/contact/"
    weight = 3


